"""Study exports generated from the solved-problem store, committed under study/:

  - study/anki.tsv   — import into Anki (front = problem, back = your approach)
  - study/notion.csv — import into Notion as a database
  - study/revise.md  — spaced-repetition list of problems due for review

Turns the archive into an interview-prep toolkit. Degrades gracefully on older
entries that lack approach/tags.
"""
from __future__ import annotations

import csv
import io
from datetime import datetime, timezone


def _date(ts):
    if not ts:
        return None
    try:
        return datetime.fromtimestamp(int(ts), tz=timezone.utc).date()
    except Exception:  # noqa: BLE001
        return None


def _html(s: str) -> str:
    return (s or "").replace("\t", " ").replace("\r", "").replace("\n", "<br>").strip()


def anki_tsv(items: list) -> str:
    lines = ["#separator:tab", "#html:true", "#tags column:3"]
    for i in items:
        title, plat, diff = i.get("title", ""), i.get("platform", ""), i.get("difficulty", "")
        front = f"{title} — {plat}" + (f" ({diff})" if diff else "")
        back = i.get("approach", "") or "Open the solution to review your approach."
        if i.get("url"):
            back += f"<br><br><a href='{i['url']}'>Problem link</a>"
        tags = " ".join(i.get("tags") or [])
        lines.append(f"{_html(front)}\t{_html(back)}\t{tags}")
    return "\n".join(lines) + "\n"


def notion_csv(items: list) -> str:
    buf = io.StringIO()
    w = csv.writer(buf)
    w.writerow(["Title", "Platform", "Difficulty", "Language", "Tags", "Solved", "Link", "Approach"])
    for i in sorted(items, key=lambda x: x.get("timestamp", 0), reverse=True):
        d = _date(i.get("timestamp"))
        w.writerow([i.get("title", ""), i.get("platform", ""), i.get("difficulty", ""),
                    i.get("lang", ""), ", ".join(i.get("tags") or []),
                    d.isoformat() if d else "", i.get("url", ""),
                    (i.get("approach", "") or "").replace("\n", " ").strip()])
    return buf.getvalue()


def revise_md(items: list, due_days: int = 21) -> str:
    today = datetime.now(timezone.utc).date()
    dated = [(i, _date(i.get("timestamp"))) for i in items]
    due = sorted([(i, d) for i, d in dated if d and (today - d).days >= due_days], key=lambda x: x[1])
    out = ["# 🔁 Revise these\n",
           f"> Problems you solved **{due_days}+ days ago** — good candidates to redo from memory.\n"]
    if not due:
        out.append("_Nothing due yet — keep solving!_")
    else:
        out.append("| Problem | Solved | Days ago |")
        out.append("|:--|:--:|:--:|")
        for i, d in due:
            dd = i.get("dir")
            title = i.get("title", "—")
            name = f"[{title}](../{dd})" if dd else title
            out.append(f"| {name} | {d.isoformat()} | {(today - d).days} |")
    out.append("\n<sub>Generated by GitKosh.</sub>")
    return "\n".join(out) + "\n"


def export_files(items: list) -> dict:
    if not items:
        return {}
    return {
        "study/anki.tsv": anki_tsv(items),
        "study/notion.csv": notion_csv(items),
        "study/revise.md": revise_md(items),
    }
