"""Generate the codesync app icon + an embedded header logo.

Produces:
  - dist_icon/icon_1024.png      (master, for .icns via iconutil)
  - app/logo_data.py             (base64 of a 72px logo for the GUI header)
Theme: indigo gradient rounded square + white circular "sync" arrows.
"""
import base64
import math
import os

from PIL import Image, ImageDraw

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dist_icon")
APP_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "app")
S = 1024
TOP = (129, 140, 248)   # indigo-400
BOT = (79, 70, 229)     # indigo-600
WHITE = (255, 255, 255, 255)


def rad(d):
    return math.radians(d)


def arrowhead(draw, cx, cy, R, theta_deg, size, width):
    th = rad(theta_deg)
    px, py = cx + R * math.cos(th), cy + R * math.sin(th)
    tx, ty = -math.sin(th), math.cos(th)          # tangent (clockwise)
    rx, ry = math.cos(th), math.sin(th)           # radial
    tip = (px + tx * size, py + ty * size)
    left = (px + rx * (width * 0.95), py + ry * (width * 0.95))
    right = (px - rx * (width * 0.95), py - ry * (width * 0.95))
    draw.polygon([tip, left, right], fill=WHITE)


def build():
    os.makedirs(OUT_DIR, exist_ok=True)
    # macOS icons leave a transparent margin (~10%); art occupies the inset square.
    margin = 100
    x0, y0 = margin, margin
    side = S - 2 * margin            # ~824
    x1, y1 = x0 + side, y0 + side

    # vertical gradient (full canvas; masked to the inset rounded square below)
    grad = Image.new("RGBA", (S, S))
    gd = ImageDraw.Draw(grad)
    for y in range(S):
        t = y / S
        gd.line([(0, y), (S, y)], fill=(
            int(TOP[0] * (1 - t) + BOT[0] * t),
            int(TOP[1] * (1 - t) + BOT[1] * t),
            int(TOP[2] * (1 - t) + BOT[2] * t), 255))
    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle([x0, y0, x1, y1], radius=int(side * 0.225), fill=255)
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    img.paste(grad, (0, 0), mask)

    d = ImageDraw.Draw(img)
    cx = cy = S // 2
    R = int(side * 0.28)            # scaled to the inset art
    w = int(side * 0.08)
    box = [cx - R, cy - R, cx + R, cy + R]
    d.arc(box, start=35, end=175, fill=WHITE, width=w)
    d.arc(box, start=215, end=355, fill=WHITE, width=w)
    arrowhead(d, cx, cy, R, 175, int(side * 0.145), w / 2 + side * 0.025)
    arrowhead(d, cx, cy, R, 355, int(side * 0.145), w / 2 + side * 0.025)
    dot = int(side * 0.068)
    d.ellipse([cx - dot, cy - dot, cx + dot, cy + dot], fill=WHITE)

    master = os.path.join(OUT_DIR, "icon_1024.png")
    img.save(master)
    print("wrote", master)

    # header logo (72px) -> base64 into app/logo_data.py
    small = img.resize((72, 72), Image.LANCZOS)
    sp = os.path.join(OUT_DIR, "logo_72.png")
    small.save(sp)
    b64 = base64.b64encode(open(sp, "rb").read()).decode("ascii")
    with open(os.path.join(APP_DIR, "logo_data.py"), "w") as f:
        f.write('"""Embedded header logo (base64 PNG) — generated by tools/make_icon.py."""\n')
        f.write(f'LOGO_PNG_B64 = "{b64}"\n')
    print("wrote app/logo_data.py")


if __name__ == "__main__":
    build()
